# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testLinearHelpersInit <- function(retrms_, tau) {
    .Call('rBalm_testLinearHelpersInit', PACKAGE = 'rBalm', retrms_, tau)
}

testLinearThetaFilling <- function(retrms_) {
    .Call('rBalm_testLinearThetaFilling', PACKAGE = 'rBalm', retrms_)
}

rBalmTestNuPriors <- function() {
    .Call('rBalm_rBalmTestNuPriors', PACKAGE = 'rBalm')
}

beadListTest <- function(x_bead_list, x) {
    .Call('rBalm_beadListTest', PACKAGE = 'rBalm', x_bead_list, x)
}

beadListMcmcTest <- function(r_bead_list, r_chain_ctl) {
    .Call('rBalm_beadListMcmcTest', PACKAGE = 'rBalm', r_bead_list, r_chain_ctl)
}

testSolver <- function(r_linear_terms) {
    .Call('rBalm_testSolver', PACKAGE = 'rBalm', r_linear_terms)
}

testMvNormSim <- function(omega, tau, n) {
    .Call('rBalm_testMvNormSim', PACKAGE = 'rBalm', omega, tau, n)
}

testCholeskyFill <- function() {
    .Call('rBalm_testCholeskyFill', PACKAGE = 'rBalm')
}

